name: Test GitHub Actions

on:
  push:
    branches:
      - dev  # ✅ dev 브랜치에 Push하면 실행됨

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Hello World
        run: echo "✅ GitHub Actions is working!"
